#!/bin/bash

if [[ $USER == "ryan" ]]
then
    export KASKADE_FILTER=ANALYTICS,TEST,NIBB,Reporting
elif [[ $USER == "alex" ]]
then
    export KASKADE_FILTER=ANALYTICS
else
    echo "Please set up your user here! $USER"
    exit
fi

if [ $1 ]
then
    if [[ $1 == "debug" ]]
    then
        ./kaskade --debug
    elif [[ $1 == "test" ]]
    then
        ./kaskade --test
    fi
else
    ./kaskade
fi
