#!/bin/bash

if [[ $USER == "ryan" ]]
then
    export KASKADE_FILTER=ANALYTICS,TEST,NIBB,MISSION_CONTROL,CHAT_PLUGIN,MS_CHAT_INVITATION
elif [[ $USER == "suitupalex" ]]
then
    export KASKADE_FILTER=ANALYTICS
elif [[ $USER == "vagrant" ]]
then
    export KASKADE_FILTER=INVITATION,PLUGIN,CONTACT
else
    echo "Please set up your user here! $USER"
    exit
fi

if [ $1 ]
then
    if [[ $1 == "debug" ]]
    then
        ./kaskade --debug
    elif [[ $1 == "test" ]]
    then
        ./kaskade --test
    elif [[ $1 == "slow" ]]
    then
        ./kaskade --slow
    fi
else
    ./kaskade
fi
